# Generated by Django 2.0.4 on 2018-06-24 17:33

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_auto_20180624_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
